# Este workflow analisa os findings de Code Scanning do GitHub usando o modelo TinyLlama
# rodando localmente em um container Ollama.
name: Analisar Findings de Segurança com TinyLlama

on:
  # O 'pull_request_target' é usado para garantir que o GITHUB_TOKEN tenha permissões de escrita
  # (pull-requests: write) necessárias para comentar no PR.
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - '*'
  # Adicione 'workflow_dispatch' para poder rodar manualmente para testes
  workflow_dispatch:

permissions:
  # Necessário para ler o código (checkout) e os eventos de segurança
  contents: read
  security-events: read
  # Necessário para comentar no Pull Request
  pull-requests: write

jobs:
  analyze-findings:
    name: Analisar Findings de Segurança com TinyLlama
    # Usamos um runner ubuntu-latest que já vem com Docker pré-instalado
    runs-on: ubuntu-latest
    
    steps:
      # Etapa 1: Checkout do código do Pull Request
      # Usamos o SHA do HEAD do PR para checkout, garantindo a segurança ao usar pull_request_target
      - name: Checkout repositório com segurança
        uses: actions/checkout@v4
        with:  # CORREÇÃO: Adicionando os dois pontos (:)
          # É crucial verificar o código que está sendo proposto
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      # Etapa 2: Instalar Ollama e TinyLlama em background
      - name: Iniciar Ollama e Pull TinyLlama
        # O docker-cli está disponível no runner. Iniciamos o Ollama expondo a porta 11434
        run: |
          echo "🐳 Iniciando container Ollama em background..."
          # Roda o Ollama em detached mode, expondo a porta 11434
          docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
          
          # Puxa o modelo TinyLlama. Isso pode levar um tempo.
          echo "⬇️ Puxando modelo tinyllama..."
          docker exec ollama ollama pull tinyllama
          
          # Espera um pouco para garantir que o serviço de API esteja ativo
          echo "⏱️ Aguardando 15 segundos para o Ollama inicializar a API..."
          sleep 15
          
          # Health check básico: verifica se o modelo está carregado (opcional, mas bom)
          docker exec ollama ollama run tinyllama "Hello" || true

      # Etapa 3: Baixar findings de Code Scanning
      - name: Baixar findings de Code Scanning
        id: download_findings
        run: |
          # Cria o diretório para armazenar os JSONs
          mkdir -p findings
          
          # Baixa apenas os alerts de Code Scanning que são abertos (state=open)
          # A lógica de parsing original é mais adequada para Code Scanning.
          echo "📥 Baixando findings de Code Scanning..."
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open" \
            -o findings/code-scanning.json
            
          # Verifica se o arquivo foi baixado e se é um JSON válido. 
          # Se o resultado for 403/404 ou um JSON vazio, o jq vai falhar, mas o script segue.
          if ! jq . findings/code-scanning.json > /dev/null 2>&1; then
              echo "[]" > findings/code-scanning.json
              echo "⚠️ Erro ou resultado vazio/inválido ao baixar Code Scanning. Criando JSON vazio."
          fi

      # Etapa 4: Analisar findings com TinyLlama
      - name: Analisar findings com TinyLlama e Comentar no PR
        # Substitui a sintaxe HERE-DOC por criação de arquivos temporários para maior robustez
        run: |
          file="findings/code-scanning.json"
          type="Code Scanning"
          
          echo "🔎 Analisando findings de ${type}..."
          
          # Conta o número de findings
          count=$(jq length "$file")

          if [ "$count" -eq 0 ]; then
            echo "✅ Nenhum finding de ${type} encontrado."
            exit 0
          fi
          
          # Loop por cada finding encontrado
          for i in $(seq 0 $(($count - 1))); do
            finding=$(jq -r ".[$i]" "$file")

            # Extração de campos (ajustei para ser mais robusto com os caminhos do jq)
            number=$(echo "$finding" | jq -r '.number // "N/A"')
            created_at=$(echo "$finding" | jq -r '.created_at // "N/A"')
            description=$(echo "$finding" | jq -r '.rule.description // "N/A"')
            severity=$(echo "$finding" | jq -r '.rule.severity // "N/A"')
            location_path=$(echo "$finding" | jq -r '.most_recent_instance.location.path // "N/A"')
            location_line=$(echo "$finding" | jq -r '.most_recent_instance.location.start_line // "N/A"')
            message_text=$(echo "$finding" | jq -r '.most_recent_instance.message.text // "N/A"')
            html_url=$(echo "$finding" | jq -r '.html_url // "N/A"')
            help_uri=$(echo "$finding" | jq -r '.rule.help_uri // "N/A"')
            
            # --- 1. Criar e preparar o Prompt ---
            # Cria o arquivo de prompt em formato multi-linha (substituindo HERE-DOC)
            # Adicionamos '--' ao printf para evitar que hífens no início da string sejam interpretados como opções
            printf "A vulnerability was found in the repository's Code Scanning. Below are the details:\n\n" > prompt.txt
            printf -- "- Finding ID: %s\n" "$number" >> prompt.txt
            printf -- "- Created At: %s\n" "$created_at" >> prompt.txt
            printf -- "- Description: %s\n" "$description" >> prompt.txt
            printf -- "- Severity: %s\n" "$severity" >> prompt.txt
            printf -- "- File Path: %s\n" "$location_path" >> prompt.txt
            printf -- "- Line Number: %s\n" "$location_line" >> prompt.txt
            printf -- "- Message: %s\n\n" "$message_text" >> prompt.txt
            printf "Do you consider this a false positive? Justify your answer briefly in Portuguese, focusing on the file and line number provided.\n\n" >> prompt.txt
            printf "For reference, here is the rule documentation: %s\n" "$help_uri" >> prompt.txt
            printf "GitHub Finding Link: %s" "$html_url" >> prompt.txt
            
            # Escapa o conteúdo do prompt para JSON e salva no arquivo final
            escaped_prompt=$(jq -Rs . prompt.txt)
            
            # Monta o payload JSON para o cURL (a chave 'prompt' usará o conteúdo escapado)
            echo "{\"model\": \"tinyllama\", \"stream\": false, \"prompt\": $escaped_prompt}" > payload.json
            
            # --- 2. Chamar a API do Ollama com retries ---
            MAX_RETRIES=3
            HTTP_CODE="0"
            result=""

            for attempt in $(seq 1 $MAX_RETRIES); do
                echo "🔌 Tentativa $attempt de conexão com Ollama..."
                response=$(curl -s -X POST http://localhost:11434/api/generate \
                  -H "Content-Type: application/json" \
                  -d @payload.json \
                  --write-out "%{http_code}" \
                  --output response.json)
                
                HTTP_CODE="${response: -3}"
                
                if [ "$HTTP_CODE" -eq 200 ]; then
                    echo "✅ Sucesso na conexão com Ollama."
                    break
                fi
                
                echo "❌ Ollama retornou código HTTP $HTTP_CODE. Tentando novamente em 5 segundos..."
                sleep 5
                
                if [ "$attempt" -eq "$MAX_RETRIES" ]; then
                    echo "🚨 Falha ao conectar ao Ollama após $MAX_RETRIES tentativas."
                    result="Não foi possível obter a análise da IA devido a falha de conexão com o TinyLlama."
                    break
                fi
            done

            # Se o curl foi bem-sucedido (código 200), extrai a resposta
            if [ "$HTTP_CODE" -eq 200 ]; then
                result=$(jq -r '.response // .error // "Resposta da IA em formato inesperado."' response.json)
            fi

            echo "🧠 Resultado da IA para Finding #$number: $result"
            
            # --- 3. Comentar no Pull Request (também sem HERE-DOC) ---
            if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
              
              # Cria o corpo do comentário em Markdown em um arquivo temporário
              printf "### 🤖 Análise Automática da TinyLlama (Code Scanning)\n\n" > comment_body.md
              printf "**Finding ID:** #%s\n" "$number" >> comment_body.md
              printf "**Severidade:** %s\n" "$severity" >> comment_body.md
              printf "**Caminho:** \`%s:%s\`\n\n" "$location_path" "$location_line" >> comment_body.md
              printf "**Descrição do Finding:**\n" >> comment_body.md
              printf "> %s\n\n" "$description" >> comment_body.md
              printf "**Resultado da IA:**\n" >> comment_body.md
              printf "\`\`\`\n%s\n\`\`\`\n\n" "$result" >> comment_body.md
              printf "[🔗 Ver finding no GitHub](%s)\n" "$html_url" >> comment_body.md
              
              # Escapa o corpo do comentário para ser injetado no payload JSON do GitHub API
              escaped_body=$(jq -Rs . comment_body.md)

              # Monta o payload JSON para o cURL (a chave 'body' usará o conteúdo escapado)
              echo "{\"body\": $escaped_body}" > comment_payload.json

              # Envia o comentário para o Pull Request
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Content-Type: application/json" \
                  -X POST \
                  -d @comment_payload.json \
                  "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
              
              echo "📝 Comentário postado no PR #${{ github.event.pull_request.number }}"

            else
              echo "⏭️ Ignorando postagem de comentário. O workflow não está rodando em um evento pull_request_target."
            fi
            
          done


      # Etapa 5: Limpar o ambiente Ollama
      - name: Parar e remover ambiente TinyLlama
        if: always()
        run: |
          echo "🛑 Parando e removendo container Ollama..."
          docker stop ollama || true
          docker rm ollama || true
